### ISSUE TITLE
Build failure with undefined reference to `store'

### ISSUE THREAD

**Issue by DavidGriffith** [Logicalshift/zoom#11]
````
gcc  -g -O2 -Wall -finline-functions -funroll-loops -fomit-frame-pointer    -DDATADIR="\"/usr/local/share/zoom\""   -o zoom  main.o interp.o file.o options.o zmachine.o zscii.o display.o xdisplay.o hash.o tokenise.o stream.o font3.o state.o rc.o rc_parse.o rc_lex.o menu.o xfont.o windisplay.o winfont.o random.o format.o v6display.o carbondisplay.o carbonfont.o carbonsupport.o carbonprefs.o debug.o eval.o iff.o blorb.o image_libpng.o image_ximage.o image_carbon.o image_none.o  -lfontconfig -lm   -lSM -lICE   -lX11 -lXext -lXrender  -lz -lpng
/usr/bin/ld: interp.o: in function `zmachine_runsome':
/disk1/home/dave/proj/int-fiction/terps/zoom/src/../src/zcode.ops:2649: undefined reference to `store'
/usr/bin/ld: /disk1/home/dave/proj/int-fiction/terps/zoom/src/../src/zcode.ops:2654: undefined reference to `store'
/usr/bin/ld: /disk1/home/dave/proj/int-fiction/terps/zoom/src/../src/zcode.ops:3397: undefined reference to `store'
/usr/bin/ld: /disk1/home/dave/proj/int-fiction/terps/zoom/src/../src/zcode.ops:3341: undefined reference to `store'
/usr/bin/ld: /disk1/home/dave/proj/int-fiction/terps/zoom/src/../src/zcode.ops:3139: undefined reference to `store'
/usr/bin/ld: interp.o:/disk1/home/dave/proj/int-fiction/terps/zoom/src/../src/zcode.ops:3135: more undefined references to `store' follow
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1028: zoom] Error 1
make[2]: Leaving directory '/disk1/home/dave/proj/int-fiction/terps/zoom/src'
make[1]: *** [Makefile:399: all-recursive] Error 1
make[1]: Leaving directory '/disk1/home/dave/proj/int-fiction/terps/zoom'
make: *** [Makefile:340: all] Error 2
````

I was able to get it to compile by going into `interp.c` and removing the `inline` directive from the `store()` function.

**Comment by Logicalshift** [comment]
This probably indicates a different issue, though I'm not entirely sure what as I don't get this failure when I compile Zoom myself (gcc 7.4.0/binutils 2.30). `store()` is not just marked as `inline` but it's also `static` because it's only used within `interp.c`: the linker shouldn't be required at all here and the intention is that the function is inlined at all of these locations in any case.

Does removing `static` instead of `inline` also fix the issue? I think if it does that would be the better fix, though this does imply that something strange is happening with the way the compiler is handling `static inline` functions (perhaps to do with the fact that `zmachine_runsome()` is an unusually huge machine-generated function)

**Comment by DavidGriffith** [comment]
At least with 53bf0d0e6a58bb7ab6055e7b3c9769871a539c54, that function is just marked as `inline` -- no `static` declaration.

**Comment by DavidGriffith** [comment]
I looked again and noticed that what I had was cloned from http://code.logicalshift.co.uk/zoom/zoom.git.  But that one hasn't been updated since 2008.  I cloned it again from here and all is well.
